baseURL: "https://jbingel.me"
#baseURL: "https://jonasbingel.github.io" 
title: Bingel
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
        #  url: books/
        #  weight: 5 
        #- name: Papers
        #  url: papers/
        #  weight: 2
        #- name: Courses
        #  url: courses/
        #  weight: 3
        #- name: Data
        #  url: data/
        #  weight: 4 
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6
        - name: Resources
          url: resources/
          weight: 2 
        - name: About
          url: about/
          weight: 4 
        - name: News
          url: news/
          weight: 5 

params:
    description: "I am a Computer Science Student at TU Darmstadt, Germany."
    author: Jonas Bingel
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jonas Bingel
          subtitle: "I am a Computer Science Student at [TU Darmstadt](https://www.tu-darmstadt.de), Germany."
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            #- name: Papers
            #  url: papers/
            #- name: Data
            #  url: data/
            #- name: Books
            #  url: books/
            - name: Resources
              url: resources/
            - name: About
              url: about/
            - name: News 
              url: news/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        #- name: CV
        #  url: cv.pdf
        - name: Email
          url: mailto:jonas.bingel@stud.tu-darmstadt.de
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/jonasbingel
        - name: Linkedin
          url: https://linkedin.com/in/jonasbingel 
        - name: Discord
          url: https://discord.com/users/679006206458593311
        #- name: Substack
        # url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/jbingel.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jonas Bingel"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2